BEGIN;

DELETE FROM upgrades 
WHERE slug IN (
    'CAT_FRIEND',
    'PUT_OUT_PAMPHLET',
    'TOO_MUCH_SAUCE',
    'GETTING_POPULAR',
    'JOB_FAIR_DAY',
    'CAT_BROTHER',
    'CAT_SISTER',
    'YARD_SALE',
    'BOBA_FOUNTAIN',
    'CAT_COUSIN',
    'ADVERTISE_YOUR_PLACE',
    'BRING_FAMILY',
    'MASTER_OF_SALT_BREAD',
    'NEW_RESTAURANT_2',
    'NEW_RESTAURANT'
);

COMMIT;