BEGIN;

DELETE FROM food_items
WHERE slug IN (
           'DIM_SUM_MENTAI', 'BOBA_TEA', 'SALTED_BREAD',
           'MATCHA_LATTE', 'STRAWBERRY_WAFFLE', 'BURNT_CHEESECAKE',
           'KLEPON', 'ONDE_ONDE', 'SERABI', 'GETUK_LINDRI'
);

COMMIT;
