BEGIN;

DELETE FROM upgrades
WHERE slug IN (
-- STG0001
   'CAT_FRIEND',
   'PUT_OUT_PAMPHLET',
   'TOO_MUCH_SAUCE',
   'GETTING_POPULAR',
   'JOB_FAIR_DAY',
   'NEW_RESTAURANT_1',

-- STG0002
   'CAT_BROTHER',
   'CAT_SISTER',
   'YARD_SALE',
   'BOBA_FOUNTAIN',
   'CAT_COUSIN',
   'ADVERTISE_YOUR_PLACE',
   'BRING_FAMILY',
   'MASTER_OF_SALT_BREAD',
   'NEW_RESTAURANT_2',

-- STG0003
   'JIM_WANNA_JOIN',
   'IMPRESSIVE_CV',
   'RENOVATION_BEGIN',
   'MASTER_OF_ART_LATTE',
   'BEST_SELLER_LATTE',
   'HIRING_DAY',
   'INTERN_BOY',
   'RENOVATION_ENDED',
   'PROFESSIONAL_BAKER',
   'ENCHANTED_WAFFLE',
   'NEW_SPOT_IN_TOWN',
   'GETTING_VIRAL',
   'SUPERSPEED_EQUIPMENT',
   'FRESH_FROM_THE_OVEN',
   'NEW_RESTAURANT_3'
);

COMMIT;
