BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS coin BIGINT DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS gem BIGINT DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS last_sync_balance_at TIMESTAMPTZ DEFAULT NULL;

COMMIT;
