BEGIN;

DROP TABLE IF EXISTS rewards CASCADE;

DROP TABLE IF EXISTS user_daily_rewards CASCADE;

DROP TABLE IF EXISTS daily_rewards CASCADE;

DROP TABLE IF EXISTS reward_types CASCADE;

DROP TABLE IF EXISTS user_daily_reward_progress CASCADE;

COMMIT;
